import { Talent, TalentStatus, SubscriptionTier } from '../types';

export const demoTalents: Talent[] = [
  {
    id: '1',
    slug: 'dj-phantom-kingston',
    stage_name: 'DJ Phantom',
    bio: 'Kingston heavy-hitter with surgical blends and rare dubplates for premium rooms.',
    city: 'Kingston',
    country: 'Jamaica',
    categories: ['DJ'],
    genres: ['Dancehall', 'Reggae'],
    status: TalentStatus.APPROVED,
    visibility: true,
    featured: true,
    subscription_tier: SubscriptionTier.PRO,
    hero_image: 'https://picsum.photos/seed/dj-phantom/1200/1600',
  },
  {
    id: '2',
    slug: 'blaze-rebel-london',
    stage_name: 'Blaze Rebel',
    bio: 'Spoken word with festival-grade command and cinematic storytelling.',
    city: 'London',
    country: 'UK',
    categories: ['Poet'],
    genres: ['Spoken Word'],
    status: TalentStatus.APPROVED,
    visibility: true,
    featured: true,
    subscription_tier: SubscriptionTier.ELITE,
    hero_image: 'https://picsum.photos/seed/blaze-rebel/1200/1600',
  },
  {
    id: '3',
    slug: 'rhythm-collective-nyc',
    stage_name: 'The Rhythm Collective',
    bio: 'A full-band experience built for corporate galas and luxury brand activations.',
    city: 'New York',
    country: 'USA',
    categories: ['Band'],
    genres: ['Jazz', 'Fusion'],
    status: TalentStatus.APPROVED,
    visibility: true,
    featured: true,
    subscription_tier: SubscriptionTier.ELITE,
    hero_image: 'https://picsum.photos/seed/rhythm-collective/1200/1600',
  },
  {
    id: '4',
    slug: 'mc-hype-toronto',
    stage_name: 'MC Hype',
    bio: 'High-energy host with seamless crowd control and premium corporate polish.',
    city: 'Toronto',
    country: 'Canada',
    categories: ['Host'],
    genres: ['Hip-Hop'],
    status: TalentStatus.APPROVED,
    visibility: true,
    featured: false,
    subscription_tier: SubscriptionTier.PRO,
    hero_image: 'https://picsum.photos/seed/mc-hype/1200/1600',
  },
  {
    id: '5',
    slug: 'zara-vibes-miami',
    stage_name: 'Zara Vibes',
    bio: 'R&B vocalist delivering velvet sets for private villas and elite weddings.',
    city: 'Miami',
    country: 'USA',
    categories: ['Singer'],
    genres: ['R&B', 'Soul'],
    status: TalentStatus.APPROVED,
    visibility: true,
    featured: false,
    subscription_tier: SubscriptionTier.STARTER,
    hero_image: 'https://picsum.photos/seed/zara-vibes/1200/1600',
  },
  {
    id: '6',
    slug: 'kng-sly-berlin',
    stage_name: 'KNG SLY',
    bio: 'Bass-forward selector known for cinematic transitions and premium club sets.',
    city: 'Berlin',
    country: 'Germany',
    categories: ['DJ'],
    genres: ['House', 'Afrobeats'],
    status: TalentStatus.APPROVED,
    visibility: true,
    featured: false,
    subscription_tier: SubscriptionTier.PRO,
    hero_image: 'https://picsum.photos/seed/kng-sly/1200/1600',
  },
  {
    id: '7',
    slug: 'misty-blue-lagos',
    stage_name: 'Misty Blue',
    bio: 'Afro-jazz vocalist with a boutique band for luxury receptions.',
    city: 'Lagos',
    country: 'Nigeria',
    categories: ['Singer'],
    genres: ['Afro-Jazz', 'Soul'],
    status: TalentStatus.APPROVED,
    visibility: true,
    featured: false,
    subscription_tier: SubscriptionTier.STARTER,
    hero_image: 'https://picsum.photos/seed/misty-blue/1200/1600',
  },
  {
    id: '8',
    slug: 'the-prophet-atlanta',
    stage_name: 'The Prophet',
    bio: 'Stage poet with cinematic delivery built for intimate cultural showcases.',
    city: 'Atlanta',
    country: 'USA',
    categories: ['Poet'],
    genres: ['Spoken Word', 'Neo Soul'],
    status: TalentStatus.APPROVED,
    visibility: true,
    featured: false,
    subscription_tier: SubscriptionTier.FREE,
    hero_image: 'https://picsum.photos/seed/the-prophet/1200/1600',
  },
  {
    id: '9',
    slug: 'nova-dancers-paris',
    stage_name: 'Nova Dancers',
    bio: 'Contemporary dance troupe for luxury brand showcases and fashion week.',
    city: 'Paris',
    country: 'France',
    categories: ['Dancer'],
    genres: ['Contemporary'],
    status: TalentStatus.APPROVED,
    visibility: true,
    featured: false,
    subscription_tier: SubscriptionTier.PRO,
    hero_image: 'https://picsum.photos/seed/nova-dancers/1200/1600',
  },
  {
    id: '10',
    slug: 'sonic-tide-la',
    stage_name: 'Sonic Tide',
    bio: 'Live electronic duo blending synths and strings for upscale events.',
    city: 'Los Angeles',
    country: 'USA',
    categories: ['Band'],
    genres: ['Electronic', 'Ambient'],
    status: TalentStatus.APPROVED,
    visibility: true,
    featured: false,
    subscription_tier: SubscriptionTier.ELITE,
    hero_image: 'https://picsum.photos/seed/sonic-tide/1200/1600',
  },
  {
    id: '11',
    slug: 'isla-royale-dubai',
    stage_name: 'Isla Royale',
    bio: 'Luxury violinist for rooftop sessions and destination weddings.',
    city: 'Dubai',
    country: 'UAE',
    categories: ['Instrumentalist'],
    genres: ['Classical', 'Pop Fusion'],
    status: TalentStatus.APPROVED,
    visibility: true,
    featured: false,
    subscription_tier: SubscriptionTier.ELITE,
    hero_image: 'https://picsum.photos/seed/isla-royale/1200/1600',
  },
  {
    id: '12',
    slug: 'golden-kings-sao-paulo',
    stage_name: 'Golden Kings',
    bio: 'Percussion-forward show band for stadium-scale brand activations.',
    city: 'São Paulo',
    country: 'Brazil',
    categories: ['Band'],
    genres: ['Percussion', 'World'],
    status: TalentStatus.APPROVED,
    visibility: true,
    featured: false,
    subscription_tier: SubscriptionTier.PRO,
    hero_image: 'https://picsum.photos/seed/golden-kings/1200/1600',
  },
];

export const featuredTalents = demoTalents.filter((talent) => talent.featured);

export const getTalentBySlug = (slug: string) =>
  demoTalents.find((talent) => talent.slug === slug);
